#' GWAS top hits for arachidonic acid in the CHARGE consortium after post-GWAS cleaning
#'
#' The dataset contains rsids for single nucleotide polymorphisms extracted from a genome-wide association study of arachidonic acid in the CHARGE consortium. Prior to extraction of the rsids, SNPs were excluded if they had a minor allele frequency <=5%, an imputation r2 score <=0.5 or were present in only 1 study (out of a total of 5 studies in the meta-analysis). This filtering steps are based on the post-GWAS filtering steps described in Guan et al (PMID=24823311). The list of rsids was then generated by: 1) extracting all SNPs with P values <5e-8 (219 SNPs in total); and then 2) performing LD clumping on the 219 extracted SNPs (clump_r2 = 0.01, clump_kb=10000 ) using European participants from UK Biobank as a reference dataset (6 SNPs remained after LD clumping). Clumping was performed using ieugwasr::ld_clump.   
#'
#' @format A charactor vector of length 6:
#' @source \url{http://www.chargeconsortium.com/main/results}
"charge_top_hits_cleaned"



  